#!/bin/sh
LIB=/usr/local/java/lib
java -server -cp /Users/hickst/lang/clojure/mayancal/test:/Users/hickst/lang/clojure/mayancal/test-resources:/Users/hickst/lang/clojure/mayancal/src:/Users/hickst/lang/clojure/mayancal/classes:/Users/hickst/lang/clojure/mayancal/resources:/Users/hickst/lang/clojure/mayancal/lib/clojure-1.3.0.jar:${LIB}/jline.jar: jline.ConsoleRunner clojure.main $*
