#!/bin/sh
clj3 -cp /Users/hickst/lang/clojure/mayancal/test \
     -cp /Users/hickst/lang/clojure/mayancal/test-resources \
     -cp /Users/hickst/lang/clojure/mayancal/src \
     -cp /Users/hickst/lang/clojure/mayancal/classes \
     -cp /Users/hickst/lang/clojure/mayancal/resources \
     -cp /Users/hickst/lang/clojure/mayancal/lib/clojure-1.3.0.jar \
     -cp /Users/hickst/lang/clojure/mayancal/lib/itextpdf-5.1.3.jar \
     -cp /Users/hickst/lang/clojure/mayancal/lib/tools.cli-0.2.1.jar \
     -cp /Users/hickst/lang/clojure/mayancal/lib/xmlworker-1.1.1.jar
