#!/bin/sh
LIB=/usr/local/java/lib
java -cp /Users/hickst/lang/clojure/mayancal/test:/Users/hickst/lang/clojure/mayancal/test-resources:/Users/hickst/lang/clojure/mayancal/src:/Users/hickst/lang/clojure/mayancal/classes:/Users/hickst/lang/clojure/mayancal/resources:/Users/hickst/lang/clojure/mayancal/lib/clojure-1.3.0.jar:/Users/hickst/lang/clojure/mayancal/lib/itextpdf-5.1.3.jar:/Users/hickst/lang/clojure/mayancal/lib/tools.cli-0.2.1.jar:/Users/hickst/lang/clojure/mayancal/lib/xmlworker-1.1.1.jar:${LIB}/jline.jar jline.ConsoleRunner clojure.main $*
